version: "3.0"
services:
  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    image: phone-numbers:backend
    container_name: phone-numbers-be
    command: ./mvnw spring-boot:run

  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    image: phone-numbers:frontend
    container_name: phone-numbers-fe
    command: npm start

